version: '3.8'

services:
  java-app:
    build: .
    container_name: "javatutorials"
    ports:
      - "8090:8090"
    depends_on:
      - mysql-db
    networks:
      - java-javatutorials-nw
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/java_tutorials"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Sanjay@123"
    restart: always
    healthcheck: 
        test: ["CMD-SHELL", "curl -f http://localhost:8090 || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 60s

  mysql-db:
    image: mysql:8
    container_name: "mysql-tutorial"
    environment:
      MYSQL_ROOT_PASSWORD: "Sanjay@123"
      MYSQL_DATABASE: "java_tutorials"
    ports:
      - "3307:3306"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - java-javatutorials-nw
    restart: always
    healthcheck: 
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pSanjay@123"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 60s
        
volumes:
  mysql_data:

networks:
  java-javatutorials-nw:
